### ISSUE TITLE
Can't exit terminal.

### ISSUE THREAD

**Issue by mauro-balades** [omegaui/omegaide#10]
![image](https://user-images.githubusercontent.com/91018726/147356007-45cbad62-aabc-4d4c-9a62-5a90153a3779.png)

It stays there forever.

**Comment by omegaui** [comment]
Exiting the Terminal does not closes its Tab!
But in the Background it gets stopped so you cannot run any more command.

So, you need to manually close its Tab.

I didn't put this thing already so as to retain the output even after exiting the terminal.
![Screenshot from 2021-12-24 21-16-52](https://user-images.githubusercontent.com/73544069/147362945-0d980528-9444-4075-85a8-f69c1bc300d0.png)

**Comment by mauro-balades** [comment]
I think it would be better if you close it.

**Comment by omegaui** [comment]
Ok!
I will fix this in the upcoming commits
