### ISSUE TITLE
How do I choose a project?

### ISSUE THREAD

**Issue by mauro-balades** [omegaui/omegaide#11]
When I browse a folder or type one. It does not "recognize" it or "add" it. Like it does not select that folder

**Comment by omegaui** [comment]
Can you please tell me on which Platform you are?
And Please provide some screenshots.

In the FileSelectionDialog you need to type the full path to open your project or you can just simply single click the folder and click done!.
Like this.

![Screenshot from 2021-12-24 21-14-22](https://user-images.githubusercontent.com/73544069/147362843-84ea6349-5fe7-4f70-8b23-ac257d0950e1.png)

**Comment by omegaui** [comment]
I will fix this so that,
the `FileSelectionDialog` also checks for folders in current directory when using the path.

**Comment by mauro-balades** [comment]
let me make a video...

**Comment by omegaui** [comment]
You **don't** need to **"double-click"** to select a folder
**"double-click"** resets the selection and changes the directory
You need to **"single-click"** the folder to select it as a workspace!

**Comment by mauro-balades** [comment]
hm... Well that is confusing...

**Comment by omegaui** [comment]
Click the folder,
It will get highlighted
and then click Done!

**Comment by mauro-balades** [comment]
let me try...

**Comment by omegaui** [comment]
Ok...👀

**Comment by mauro-balades** [comment]
It works!!!

**Comment by mauro-balades** [comment]
btw, do you have any place where you can talk?

**Comment by omegaui** [comment]
Instagram

**Comment by omegaui** [comment]
[insta](https://www.instagram.com/i_am_arham_92/)

**Comment by mauro-balades** [comment]
I don't have Instagram :(

**Comment by omegaui** [comment]
Or Whatsapp

**Comment by omegaui** [comment]
How about Github Discussions?
Or Something that works on your side

**Comment by mauro-balades** [comment]
> How about Github Discussions?

yea!

**Comment by omegaui** [comment]
Ok Let me create one!

**Comment by omegaui** [comment]
(discuss)[https://github.com/omegaui/omegaide/discussions/14]

**Comment by omegaui** [comment]
[discuss](https://github.com/omegaui/omegaide/discussions/14)
