### ISSUE TITLE
PROCESSES ARE NOT LAUNCHING

### ISSUE THREAD

**Issue by SaadAhmad04** [omegaui/omegaide#19]
![2022-01-08 (8)](https://user-images.githubusercontent.com/97330468/148635173-a8b7f218-409e-470b-a65d-1e7f8de89d18.png)

**Comment by omegaui** [comment]
I think you have combined the data files of an earlier build of omegaide with a recent build.
To fix
 **delete** the **.generated-pty4j-libs...** file located in `.omega-ide` directory.
And launch the IDE again.
