### ISSUE TITLE
Would like to contribute, but don't know what would be good for the project

### ISSUE THREAD

**Issue by marcelovbcfilho** [omegaui/omegaide#21]
**Is your feature request related to a problem? Please describe.**
Would like to contribute, but don't know what and which would be good for the project.

**Describe the solution you'd like**
I would imagine that a discord, or a channel to communicate and interact with the developers, to avoid doing things that aren't intended.

**Describe alternatives you've considered**
Create a development guideline with changes that would be considered to be merged and changes that aren't going to be accepted.

**Additional context**
For example, after I downloaded the IDE, the fact that it uses a custom window control system bothered me, so I downloaded the source code and change it, to use native ones and also moved the memory usage to the right, but don't if this is the goal or the design guidelines that you, developers, would like to follow, image of what I did, but as I said, would like to have a channel, goals or a design guidelines of what would be accepted in a Pull Request.

Obs: Image of what I did, just as an example of something that for me would be better, but could not be the project goal. As I said, removed custom window control and moved the memory usage to the right, that for me makes sense, but don't know what you guys think.
![Screenshot from 2022-03-19 19-07-52](https://user-images.githubusercontent.com/51462138/159140093-1018f319-64f0-4678-9c91-5d22a8e3a2ae.png)

**Comment by omegaui** [comment]
Thanks!

A Critical thing that omegaide is lacking is a Refraction Framework.

**Comment by omegaui** [comment]
[Only this thing left for v2.2-beta to reach stable](https://github.com/users/omegaui/projects/1)

**Comment by omegaui** [comment]
@marcelovbcfilho 
Thanks for purposing the guidelines part.
But I think the CONTRIBUTING.md and [this](https://github.com/omegaui?tab=projects) describes everything.
