### ISSUE TITLE
Support for Android

### ISSUE THREAD

**Issue by kaicsm** [omegaui/omegaide#35]
Would it be possible to introduce support for Android? The IDE is written in Java, I believe it is possible with correct layout adaptations for Android. The current competitors in the context of code editor or IDE would be `acode` and `android ide` which are good in their areas. However, none are capable of providing IDE support for any language

**Comment by omegaui** [comment]
Hi! @kaicsalomao 
I appreciate your idea.

omega-ide was my first project that I wrote which eventually helped me to understand how an IDE can be implemented from scratch as well as the internals of programming language.

As of today, omega-ide is not being maintained actively, as I have other bigger projects going on, most them already pinned on my profile.

omega-ide is very simple to understand and it gives a simple idea for anyone wanting to learn IDE design, most particularly for Java.

Currently, I'm working on a `Generic Package Manager` that would let anyone install any github project with out-of-the-box support for updates with an extended support to build any repository from source, I call it `gpm`.

It is indeed, a big project, and I'm focussed on to complete it. As it would standardize project distribution on all of github, and it would even fill the tech-gap which new users face when installing open-source project from Github, like building the project from source, arranging dependencies, etc.

If you wish, you can give this idea of `Android Support` a try, may be adding it via the plugin system or hardcoding it in the IDE core itself.

**Comment by kaicsm** [comment]
I understand, your current project looks very interesting. I will close this issue as completed
